name: C/C++ CI

on:
  push:
      branches: [ main ]

jobs:
  build-and-test:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: make lib_prague
        run: make lib_prague 
      - name: make all
        run: make all
